import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,rm,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {prepareLocal,nextLocal,respondLocal,installLocal} from '../src/local-processing.js';
const source='Record the person responsible for each agreed action.\nAgree and record a deadline with that person.\nReview the record at the next meeting.';
const section={title:'Meeting notes',author:null,summary:'The source asks for a responsible person and agreed deadline for each action, followed by review.',sourceRefs:[{startLine:1,endLine:3}],ideas:[{name:'Record commitments',explanation:'Record an owner and agreed deadline, then review them.',whenToUse:'Recording agreed actions.',decisionRule:null,steps:['Record the responsible person.','Agree and record the deadline.','Review the record at the next meeting.'],limits:'No further boundaries are specified in this source.',sourceRefs:[{startLine:1,endLine:3}],applicationBasis:'source-instruction'}],antiPatterns:[],workedExamples:[]};
const book={oneLiner:'Record commitments and review them.',readIf:'You need to record agreed actions.',thesis:'Action records identify a responsible person and agreed deadline for later review.',tags:['meeting-notes'],year:null,glossary:[]};
async function setup(t){const root=await mkdtemp(join(tmpdir(),'awb-local-test-'));t.after(()=>rm(root,{recursive:true,force:true}));const file=join(root,'notes.txt'),dir=join(root,'work');await writeFile(file,source);await prepareLocal(file,{output:dir},{extract:async()=>({text:source,headings:[]})});const respond=async(request,value)=>{const input=join(root,'response.json');await writeFile(input,JSON.stringify(value));return respondLocal(dir,{input,request:request.id});};return {root,file,dir,respond};}
test('agent supplies every model response, progress resumes, final package installs offline as exactly one skill',async t=>{const {root,dir,respond}=await setup(t);const first=await nextLocal(dir);assert.equal(first.status,'needs_agent_response');assert.deepEqual((await nextLocal(dir)).request,first.request);await respond(first.request,section);let step=await nextLocal(dir);const claims=JSON.parse(step.request.input).claims;await respond(step.request,{supported:true,issues:[],checks:claims.map(c=>({id:c.id,supported:true,reason:'The cited passage prescribes this record.'}))});step=await nextLocal(dir);assert.equal(step.completedSections,1);await respond(step.request,book);step=await nextLocal(dir);await respond(step.request,{supported:true,issues:[]});step=await nextLocal(dir);assert.equal(step.status,'ready');assert.equal(step.customerChargeCents,0);assert.equal(await readFile(join(dir,'package/skill/source.txt'),'utf8'),source);assert.equal((await nextLocal(dir)).status,'ready');const installed=await installLocal(dir,{}, {skillsDir:join(root,'skills'),cacheRoot:join(root,'cache')});assert.equal(installed.status,'installed');const files=await readdir(installed.path,{recursive:true});assert.equal(files.filter(path=>path.endsWith('SKILL.md')).length,1);assert.match(await readFile(join(installed.path,'SKILL.md'),'utf8'),/Check the evidence/);});
test('wrong request, incomplete response and out-of-range citations do not advance or overwrite progress',async t=>{const {root,dir,respond}=await setup(t),step=await nextLocal(dir);const path=join(root,'bad.json');await writeFile(path,'{}');await assert.rejects(respondLocal(dir,{input:path,request:'wrong'}),/does not match/);await assert.rejects(respond(step.request,{}),/missing/);await assert.rejects(respond(step.request,{...section,sourceRefs:[{startLine:1,endLine:900}]}),/bounds/);assert.equal((await nextLocal(dir)).request.id,step.request.id);});
test('failed source review produces targeted repair and preserves accepted work; no silent acceptance',async t=>{const {dir,respond}=await setup(t);let step=await nextLocal(dir);await respond(step.request,section);step=await nextLocal(dir);const claims=JSON.parse(step.request.input).claims;await respond(step.request,{supported:false,issues:['Check the summary wording.'],checks:claims.map(c=>({id:c.id,supported:false,reason:'Check wording.'}))});step=await nextLocal(dir);assert.equal(step.status,'needs_repair');step=await nextLocal(dir);assert.match(step.request.input,/previousDraft/);assert.match(step.request.input,/Check the summary wording/);assert.equal(step.completedSections,0);const repairId=step.request.id;await respond(step.request,section);step=await nextLocal(dir);const retryClaims=JSON.parse(step.request.input).claims;await respond(step.request,{supported:false,issues:['Check the summary wording.'],checks:retryClaims.map(c=>({id:c.id,supported:false,reason:'Check wording.'}))});assert.equal((await nextLocal(dir)).status,'needs_repair');assert.notEqual((await nextLocal(dir)).request.id,repairId,'A repeated repair must allow a new response rather than replay a cached rejected draft.');});
